
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Wed Oct 17 23:25:43 CEST 2018
//----------------------------------------------------

package rs.ac.bg.etf.pp1.ast;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DIVIDE = 22;
  public static final int INCREMENT = 33;
  public static final int CONST = 18;
  public static final int EQUALS = 24;
  public static final int LPAREN = 37;
  public static final int GREATER = 26;
  public static final int CONTINUE = 15;
  public static final int LESS = 28;
  public static final int MINUS = 20;
  public static final int DECREMENT = 34;
  public static final int STAR = 21;
  public static final int RPAREN = 38;
  public static final int CHARACTER = 3;
  public static final int SEMICOLON = 35;
  public static final int AND = 30;
  public static final int LESSEQUAL = 29;
  public static final int OR = 31;
  public static final int BOOL = 17;
  public static final int CLASS = 6;
  public static final int PLUS = 19;
  public static final int ASSIGN = 32;
  public static final int IF = 8;
  public static final int DOT = 43;
  public static final int EOF = 0;
  public static final int RETURN = 10;
  public static final int NEW = 9;
  public static final int error = 1;
  public static final int PROGRAM = 4;
  public static final int COMA = 36;
  public static final int NUMBER = 2;
  public static final int MOD = 23;
  public static final int BREAK = 5;
  public static final int IDENT = 16;
  public static final int VOID = 11;
  public static final int LBRACK = 41;
  public static final int GREATEREQUAL = 27;
  public static final int LBRACE = 39;
  public static final int ELSE = 7;
  public static final int RBRACK = 42;
  public static final int NOTEQUALS = 25;
  public static final int WHILE = 13;
  public static final int RBRACE = 40;
  public static final int EXTENDS = 14;
  public static final int DO = 12;
}

