
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Thu Oct 04 17:42:56 CEST 2018
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int error = 1;
  public static final int PLUS = 2;
  public static final int EOF = 0;
}

