
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Tue Dec 18 13:27:00 CET 2018
//----------------------------------------------------

package rs.ac.bg.etf.pp1.ast;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DIVIDE = 25;
  public static final int INCREMENT = 36;
  public static final int CONST = 21;
  public static final int EQUALS = 27;
  public static final int LPAREN = 40;
  public static final int GREATER = 29;
  public static final int CONTINUE = 18;
  public static final int INTERFACE = 7;
  public static final int DECREMENT = 37;
  public static final int LESS = 31;
  public static final int FOR = 15;
  public static final int MINUS = 23;
  public static final int STAR = 24;
  public static final int RPAREN = 41;
  public static final int CHARACTER = 3;
  public static final int SEMICOLON = 38;
  public static final int AND = 33;
  public static final int LESSEQUAL = 32;
  public static final int OR = 34;
  public static final int BOOL = 20;
  public static final int CLASS = 6;
  public static final int PLUS = 22;
  public static final int ASSIGN = 35;
  public static final int IF = 11;
  public static final int DOT = 46;
  public static final int EOF = 0;
  public static final int RETURN = 13;
  public static final int NEW = 12;
  public static final int error = 1;
  public static final int PROGRAM = 4;
  public static final int COMA = 39;
  public static final int NUMBER = 2;
  public static final int MOD = 26;
  public static final int BREAK = 5;
  public static final int IDENT = 19;
  public static final int VOID = 14;
  public static final int LBRACK = 44;
  public static final int GREATEREQUAL = 30;
  public static final int LBRACE = 42;
  public static final int ELSE = 10;
  public static final int READ = 47;
  public static final int RBRACK = 45;
  public static final int ENUM = 9;
  public static final int NOTEQUALS = 28;
  public static final int WHILE = 16;
  public static final int RBRACE = 43;
  public static final int EXTENDS = 17;
  public static final int IMPLEMENTS = 8;
  public static final int PRINT = 48;
}

